apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: my-bucket
  labels:
    cluster: cb-example
spec:
  name: couchbaseDemo
  memoryQuota: 512Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  minimumDurability: none
---

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: my-perf-bucket
  labels:
    cluster: cb-example
spec:
  name: default
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  minimumDurability: none
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  #image: couchbase/server:6.6.0
  image: couchbase/server:7.0.2
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
    selector:
      matchLabels:
        cluster: cb-example
  cluster:
    clusterName: paris-cluster
    dataServiceMemoryQuota: 2048Mi
    indexServiceMemoryQuota: 256Mi
    searchServiceMemoryQuota: 256Mi
    eventingServiceMemoryQuota: 256Mi
    analyticsServiceMemoryQuota: 1Gi
    autoFailoverTimeout: 10s
    autoFailoverMaxCount: 2
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 20s
    autoFailoverServerGroup: false
  servers:
  - size: 3
    name: server
    services:
    - data
  - size: 2
    name: query_index
    services:
    - index
    - query
